### source: https://github.com/padmalcom/Real-Time-Voice-Cloning-German
### own changes and adjustments marked with "# modified by AVI" in comment
#
#Copyright (c) padmalcom
#
# MIT License
#
# Modified & original work Copyright (c) 2019 Corentin Jemine (https://github.com/CorentinJ)
# Original work Copyright (c) 2018 Rayhane Mama (https://github.com/Rayhane-mamah)
# Original work Copyright (c) 2019 fatchord (https://github.com/fatchord)
# Original work Copyright (c) 2015 braindead (https://github.com/braindead)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

### MODIFIED BY AVI for Linux-64

name: voice_cloning
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.0
  - libsqlite=3.43.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.43.0
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - annotated-types==0.5.0
      - appdirs==1.4.4
      - audioread==3.0.1
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - contourpy==1.1.1
      - cycler==0.12.0
      - decorator==5.1.1
      - dill==0.3.7
      - fonttools==4.43.0
      - idna==3.4
      - inflect==7.0.0
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.0
      - matplotlib==3.8.0
      - msgpack==1.0.7
      - multiprocess==0.70.15
      - networkx==3.1
      - numba==0.58.0
      - numpy==1.25.2
      - packaging==23.2
      - pillow==10.0.1
      - platformdirs==3.10.0
      - pooch==1.7.0
      - pycparser==2.21
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - python-dateutil==2.8.2
      - pyzmq==25.1.1
      - requests==2.31.0
      - resampy==0.4.2
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - six==1.16.0
      - sounddevice==0.4.6
      - soundfile==0.12.1
      - soxr==0.3.6
      - tbb==2021.10.0
      - threadpoolctl==3.2.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - umap-learn==0.5.4
      - unidecode==1.3.7
      - urllib3==2.0.5
      - visdom==0.2.4
      - webrtcvad==2.0.10
      - websocket-client==1.6.3
